CREATE TABLE IF NOT EXISTS typedocuments (
TYPEDOCUMENT_ID bigint(5) AUTO_INCREMENT,
TITRE varchar(25) NOT NULL, 
DESCRIPTION varchar(25) NOT NULL,
DATE_CREATION DATE,
DATE_LAST_UPDATE DATE,
PRIMARY KEY(TYPEDOCUMENT_ID)
)
;