CREATE TABLE IF NOT EXISTS typearticles (
TYPEARTICLE_ID bigint(5) AUTO_INCREMENT,
TITRE varchar(25) NOT NULL, 
DESCRIPTION varchar(25) NOT NULL,
DATE_CREATION DATE,
DATE_ARCHIVAGE DATE,
PRIMARY KEY(TYPEARTICLE_ID)
)
;