CREATE TABLE IF NOT EXISTS articles (
ARTICLE_ID bigint(5) AUTO_INCREMENT,
TITRE varchar(25) NOT NULL,
AUTEUR_ID varchar(255), 
AUTEUR_USERNAME varchar(25) NOT NULL, 
DATE_CREATION DATE, 
DATE_PUBLICATION DATE,
DATE_MODERATION DATE,
DATE_ARCHIVAGE DATE, 
IMAGE varchar(25), 
CONTENU varchar(255) NOT NULL,
ENTETE varchar(50) NOT NULL, 
STATUT_DOCUMENT int(3),
TYPEARTICLE_ID bigint(5),
IS_MODERATED BOOLEAN,
PRIMARY KEY (ARTICLE_ID),
KEY TYPEARTICLE_ID (TYPEARTICLE_ID),
CONSTRAINT ARTICLES_IFBK_1 FOREIGN KEY (TYPEARTICLE_ID) REFERENCES typearticles (TYPEARTICLE_ID)
)
;
