CREATE TABLE IF NOT EXISTS propositions (
  PROPOSITION_ID bigint(5) AUTO_INCREMENT,
  EMETTEUR_ID bigint(5) NOT NULL,
  TRADE_TYPE int(5),
  TITRE varchar(100) NOT NULL,
  DESCRIPTION varchar(255) NOT NULL,
  IMAGE varchar(30),
  VILLE varchar(50) NOT NULL,
  CODE_POSTAL int(6) NOT NULL,
  VALEUR int(3) NOT NULL,
  DATE_FIN DATE,
  DATE_ECHEANCE DATE,
  STATUT int(5),
  CATEGORIE_ID bigint(5),
  DATE_DEBUT DATE,
  PRIMARY KEY (PROPOSITION_ID), 
  KEY CATEGORIE_ID (CATEGORIE_ID),
  CONSTRAINT PROPOSITIONS_IFBK_1 FOREIGN KEY (CATEGORIE_ID) REFERENCES categories (CATEGORIE_ID)
  );
  
  
  
   
