CREATE TABLE IF NOT EXISTS echanges (
  ECHANGE_ID bigint(5),
  DATE_ENREGISTREMENT DATE,
  STATUT int(5),
  DATE_CONFIRMATION DATE,
  DATE_ANNULATION DATE,
  AVIS_EMETTEUR int(5), 
  AVIS_RECEPTEUR int(5),
  DATE_FIN DATE,
  COMMENT_EMETTEUR varchar(130),
  COMMENT_RECEPTEUR varchar (130),
  NOTE_EMETTEUR int(5),
  NOTE_RECEPTEUR int(5),
  KEY REPONSE_ECHANGE (ECHANGE_ID),
  CONSTRAINT ECHANGE_ID FOREIGN KEY (ECHANGE_ID) REFERENCES reponses (REPONSE_ID) ON DELETE CASCADE ON UPDATE CASCADE
);


  
  