CREATE TABLE IF NOT EXISTS transactions (
  TRANSACTION_ID bigint(5),
  MONTANT int(3),
  DATE_TRANSACTION DATE,
  KEY ECHANGE_TRANSACTION (TRANSACTION_ID),
  CONSTRAINT TRANSACTION_ID FOREIGN KEY (TRANSACTION_ID) REFERENCES echanges (ECHANGE_ID) ON DELETE CASCADE ON UPDATE CASCADE
);



