CREATE TABLE IF NOT EXISTS transactions_wallets (
TRANSACTION_ID bigint(5),
WALLET_ID bigint(5),
FOREIGN KEY (TRANSACTION_ID) REFERENCES transactions (TRANSACTION_ID) ON DELETE RESTRICT ON UPDATE CASCADE,
FOREIGN KEY (WALLET_ID) REFERENCES wallets (WALLET_ID) ON DELETE RESTRICT ON UPDATE CASCADE,
PRIMARY KEY (TRANSACTION_ID, WALLET_ID)
);