CREATE TABLE IF NOT EXISTS evaluations (
  EVALUATION_ID bigint(5) AUTO_INCREMENT,
  ADHERENT_ID bigint(5) NOT NULL,
  ADHERENT_USERNAME varchar(25) NOT NULL,
  COMMENTAIRE varchar(255) NOT NULL,
  NOTE int(3),
  DATE_EVALUATION DATE,
  ECHANGE_ID bigint(5),
  PRIMARY KEY (EVALUATION_ID),
  KEY ECHANGE_ID (ECHANGE_ID),
  CONSTRAINT EVALUATIONS_IFBK_1 FOREIGN KEY (ECHANGE_ID) REFERENCES echanges (ECHANGE_ID)
  );
  